import type { Metadata } from "next";

import { LegalLayout, type LegalSection } from "@/components/legal-layout";

export const metadata: Metadata = { title: "Privacy", description: "How Regena handles information submitted through this website." };

const sections: LegalSection[] = [
  { id: "scope", title: "Scope and accountability", content: <><p>This Privacy Notice explains how Regenix Technologies Incorporated, doing business as Regena, handles personal information collected through regena.io. It covers business enquiries, clinic diagnostics, strategy-call scheduling, Careers applications, and technical information generated when the website is used.</p><p>The website is intended for business use and does not invite patients to submit health records or other sensitive medical information.</p></> },
  { id: "information", title: "Information we collect", content: <><p>You may provide your name, business contact details, clinic and operational information, diagnostic answers, professional profiles, application responses, scheduling information, and a résumé.</p><p>Hosting and security services may also process limited technical data such as IP address, device and browser information, request timestamps, referring pages, and error or security events.</p><p>Diagnostic calculations use the business figures you provide to create illustrative scenarios. They are not medical assessments or promised commercial results.</p></> },
  { id: "use", title: "How information is used", content: <><p>Regena uses personal information to respond to enquiries, provide requested diagnostic results, schedule conversations, evaluate Careers applications, operate and secure the website, maintain business records, and improve website reliability and user experience.</p><p>Regena does not sell personal information. It does not use Careers information to make automated hiring decisions.</p></> },
  { id: "careers", title: "Careers applications", content: <p>Careers applications are reviewed by the Regena team for current or reasonably related future opportunities. Résumés are stored in private file storage and are not returned through a public website response. Applicants should submit only professional information relevant to an application and should not include government identification numbers, financial account information, or health information.</p> },
  { id: "services", title: "Service providers", content: <p>Regena uses service providers to operate this website and its workflows. These include Vercel for hosting and private file storage, Resend for email delivery, Sanity for blog content, and GoHighLevel for scheduling and related customer-management workflows. Providers process information on Regena&apos;s behalf or under their own applicable terms, depending on the service.</p> },
  { id: "disclosure", title: "When information may be disclosed", content: <p>Information may be disclosed to service providers that support the purposes described above, to professional advisers, in connection with a business transaction, or when required to comply with law, protect rights and safety, prevent fraud or abuse, or enforce agreements. Regena does not disclose personal information more broadly than reasonably necessary for the purpose.</p> },
  { id: "retention", title: "Retention and security", content: <><p>Personal information is retained only as long as reasonably necessary for the purpose collected, related business records, legal requirements, dispute resolution, security, or enforcement. Retention periods vary by record type and context.</p><p>Regena uses administrative, technical, and organizational safeguards appropriate to the information. No internet transmission or storage system can be guaranteed completely secure.</p></> },
  { id: "international", title: "International processing", content: <p>Some service providers may process information outside Alberta or Canada. Information processed in another jurisdiction may be subject to that jurisdiction&apos;s laws and lawful access processes.</p> },
  { id: "rights", title: "Your choices and requests", content: <p>You may request access to or correction of personal information Regena holds about you, ask questions about its handling, or request deletion where applicable. Some information may need to be retained for legal, security, or legitimate business reasons. You may also decline non-essential follow-up communications.</p> },
  { id: "changes", title: "Changes to this Notice", content: <p>Regena may update this Notice as the website, providers, or legal requirements change. The effective date at the top of this page identifies the current version.</p> },
  { id: "contact", title: "Contact", content: <p>Privacy questions and requests can be sent to <a href="mailto:contact@regena.io">contact@regena.io</a>.</p> },
];

export default function PrivacyPage() { return <LegalLayout eyebrow="Legal" title="Privacy" description="How Regena handles website, business-contact, and Careers information." effectiveDate="September 27, 2026" sections={sections} />; }
