import type { Metadata } from "next";

import { LegalLayout, type LegalSection } from "@/components/legal-layout";

export const metadata: Metadata = { title: "Terms", description: "Terms governing use of the Regena website." };

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement and operator", content: <><p>These Terms govern access to and use of regena.io and its related pages, forms, diagnostics, and content. The website is operated by Regenix Technologies Incorporated, doing business as Regena, an Alberta corporation.</p><p>By using the website, you agree to these Terms. If you do not agree, do not use the website.</p></> },
  { id: "scope", title: "Website scope", content: <><p>The website provides general information about Regena, its services, Careers opportunities, and patient-growth systems for healthcare organizations. Website content does not create a consulting, employment, partnership, fiduciary, or client relationship.</p><p>Any services purchased from Regena are governed by a separate written agreement. If that agreement conflicts with these Terms, the signed agreement controls for those services.</p></> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may use the website only for lawful purposes. You may not attempt to gain unauthorized access, interfere with website operation, introduce malicious code, scrape the website in a way that impairs service, impersonate another person, submit false or unlawful material, or use the website to violate another person&apos;s rights.</p><p>Regena may restrict access when reasonably necessary to protect the website, its users, or its systems.</p></> },
  { id: "information", title: "Information and results", content: <><p>Website information is general business information and is not medical, legal, financial, or professional advice. Clinic diagnostics and commercial scenarios are illustrative estimates based on information supplied by the visitor. They are not guarantees of revenue, patient volume, bookings, attendance, or any other outcome.</p><p>Past or described client results may not be typical. Actual results depend on demand, capacity, services, team execution, market conditions, data quality, system access, and other factors.</p></> },
  { id: "health-information", title: "No patient or emergency use", content: <p>The website is intended for business enquiries. Do not submit patient records, health information, emergency requests, or information requiring urgent clinical attention through website forms. Regena does not provide medical diagnosis, treatment, or emergency services through this website.</p> },
  { id: "intellectual-property", title: "Intellectual property", content: <p>The website, branding, writing, interface designs, graphics, software, and other original materials are owned by or licensed to Regenix Technologies Incorporated and are protected by applicable intellectual property laws. You may view and use the website for internal business evaluation, but may not reproduce, modify, distribute, sell, or commercially exploit protected materials without written permission.</p> },
  { id: "third-party", title: "Third-party services and links", content: <p>The website may connect to or link to third-party services, including scheduling, email delivery, content management, hosting, and professional-networking platforms. Those services operate under their own terms and privacy practices. Regena is not responsible for third-party websites or services it does not control.</p> },
  { id: "availability", title: "Availability and liability", content: <><p>The website is provided on an as-is and as-available basis to the extent permitted by law. Regena does not promise uninterrupted access or that every item of information will remain current, complete, or error-free.</p><p>To the maximum extent permitted by law, Regena and its directors, officers, employees, and contractors will not be liable for indirect, incidental, special, consequential, or punitive damages arising from website use. Nothing in these Terms excludes liability that cannot lawfully be excluded.</p></> },
  { id: "law", title: "Governing law", content: <p>These Terms are governed by the laws of Alberta and the federal laws of Canada applicable in Alberta, without regard to conflict-of-law rules. Any dispute relating to the website will be brought before the courts located in Alberta unless applicable law requires otherwise.</p> },
  { id: "changes", title: "Changes to these Terms", content: <p>Regena may update these Terms as the website, services, or legal requirements change. The effective date at the top of this page identifies the current version. Continued use after an update means the revised Terms apply to that use.</p> },
  { id: "contact", title: "Contact", content: <p>Questions about these Terms can be sent to <a href="mailto:contact@regena.io">contact@regena.io</a>.</p> },
];

export default function TermsPage() { return <LegalLayout eyebrow="Legal" title="Terms" description="The rules governing use of the Regena website." effectiveDate="September 27, 2026" sections={sections} />; }
